[package]
name = "resource_control"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
core_affinity = "0.8.3"
jemallocator = "0.5.4"
sysinfo = "0.39.5"
daemonize = "0.5"
thiserror = "2"
rustix = { version = "1.1", features = ["process"] }
signal-hook = "0.3"

[dev-dependencies]
